AllCops:
  Exclude:
    - 'addons/**/*'
    - 'vendor/**/*'

# Avoid long parameter lists
ParameterLists:
  Max: 4
  CountKeywordArgs: true

MethodLength:
  CountComments: false
  Max: 14

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false

# Disallow ASCII check in comments
AsciiComments:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

EndOfLine:
  Enabled: false
