language: ruby
cache: bundler
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - ruby-head
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: jruby-18mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
branches:
  only:
    - master
    - wip
