language: ruby
cache: bundler
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - ruby-head
gemfile:
  - Gemfile
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
